Remove memmap2 dependency on wasm32 targets
RazrFalcon/fontdb pull request #17
Opened 2021-08-27 11:19 UTC by neinseg

I tried to get usvg to run on top of wasmtime with filesystem emulation.

This patch conditionally disables the memmap2 dependency on wasm32 targets and enables a fallback code path that simply uses `read_to_end`. With this patch, fontdb successfully renders text to paths on wasmtime.

Please note that this is the first rust I've written ever, so please sanity-check this before merging.

2021-08-29 10:25 UTC, neinseg commented
I've pushed a new version that does not auto-guess memmap support based on the platform anymore, and instead simply exposes a memmap-fonts feature separate from the existing fs feature. resvg/usvg can then simply forward this feature in their `Cargo.toml`s and leave it to the user to choose whether or not to enable it.

Note that I would ideally like use of memmap to be on by default, and to have a "no-memmap-fonts" feature instead, but I can't figure out an elegant way to express that in cargo's terms. It seems to me cargo does not have native support for default-on "negative" features.

2021-08-29 11:05 UTC, RazrFalcon commented on Cargo.toml
> +memmap2 = { version = "0.3", optional = true }
No need to move it down.

2021-08-29 11:11 UTC, RazrFalcon requested changes

2021-08-29 11:11 UTC, RazrFalcon commented on Cargo.toml
> +memmap-fonts = ["memmap2"]
`memmap` should be enough. No need for longer names. And add a comment like this:

```
memmap = ["memmap2"] # allows font files memory mapping, greatly improves performance 
```

2021-08-29 11:11 UTC, RazrFalcon commented on Cargo.toml
>  default = ["fs"]
Add `memmap` to default features.

2021-08-29 11:11 UTC, RazrFalcon commented on src/lib.rs
> +    #[cfg(feature = "fs")]
You can write `#[cfg(all(feature = "fs", feature = "memmap"))]`

2021-08-29 11:11 UTC, RazrFalcon commented on src/lib.rs
> +    fn load_fonts_from_file<P: AsRef<Path>>(&mut self, path: P, data : &[u8]) {
What this function does? Nothing?

2021-08-29 11:11 UTC, RazrFalcon commented on src/lib.rs
> +    #[cfg(not(feature = "memmap2"))]
`memmap` not `memmap2`

2021-08-29 11:11 UTC, RazrFalcon commented on src/lib.rs
> +                std::io::Read::read_to_end(&mut file, &mut buffer).ok()?;
You can use [`std::fs::read()`](https://doc.rust-lang.org/stable/std/fs/fn.read.html) here.

2021-08-29 11:16 UTC, RazrFalcon commented on src/lib.rs
> +    fn load_fonts_from_file<P: AsRef<Path>>(&mut self, path: P, data : &[u8]) {
Remove `<P: AsRef<Path>>` from this function. It should accept just `std::path::PathBuf`.

2021-08-29 11:17 UTC, RazrFalcon requested changes

2021-08-29 11:17 UTC, RazrFalcon commented on Cargo.toml
> +memmap-fonts = ["memmap2"]
Also, I think `memmap` should depend on `fs` too, so `["fs", "memmap2"]`

2021-08-29 20:14 UTC, neinseg commented
Thank you for the review. The latest push should clear up all of your comments.

2021-08-29 20:16 UTC, RazrFalcon requested changes

2021-08-29 20:16 UTC, RazrFalcon commented on Cargo.toml
> +memmap = ["fs", "memmap2"]
Add `# allows font files memory mapping, greatly improves performance`

2021-08-30 07:35 UTC, neinseg commented on Cargo.toml
> +memmap = ["fs", "memmap2"]
done.

2021-08-30 09:19 UTC, merged